name: CD Pipeline

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      java-version:
        required: false
        type: string
        default: "25"
      skip-seeds:
        required: false
        type: boolean
        default: false
    secrets:
      SPRING_DATASOURCE_USERNAME:
        required: true
      SPRING_DATASOURCE_PASSWORD:
        required: true
      SPRING_DATASOURCE_URL:
        required: true
      SPRING_DATASOURCE_SCHEMA:
        required: true

  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy"
        type: environment
        required: true
      java-version:
        description: "Java version to use in release and migration"
        type: string
        required: false
        default: "25"
      skip-seeds:
        description: "Whether to skip seed migrations"
        type: boolean
        required: false
        default: false

permissions:
  contents: read
  packages: write

concurrency:
  group: cd-${{ inputs.environment }}
  cancel-in-progress: false

jobs:
  release:
    uses: ./.github/workflows/release.yml
    with:
      java-version: ${{ inputs.java-version }}
    permissions:
      contents: read
      packages: write

  migrate-db:
    needs: release
    uses: ./.github/workflows/migrate-db.yml
    with:
      environment: ${{ inputs.environment }}
      java-version: ${{ inputs.java-version }}
      skip-seeds: ${{ inputs.skip-seeds }}
    secrets: inherit
